"""Count OpenStreetMap buildings per model cell (exposure layer).

Run from the repository root after downloading building centroids:
    curl -s --data-urlencode 'data=[out:json][timeout:240];(way["building"](12.9186,77.615,12.986,77.7118);relation["building"](12.9186,77.615,12.986,77.7118););out center qt;' \
      https://overpass-api.de/api/interpreter -o data/bengaluru/raw/osm-buildings.json
    python3 data/bengaluru/build_exposure.py

Counts are mapped buildings, not people: OSM coverage in Bengaluru is good but not
complete, and building size and occupancy vary widely. Data (c) OpenStreetMap
contributors, ODbL.
"""
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
terrain = json.loads((ROOT / "public/data/bengaluru/terrain.json").read_text())
grid = terrain["grid"]
raw = json.loads((ROOT / "data/bengaluru/raw/osm-buildings.json").read_text())
counts = {c["id"]: 0 for c in terrain["cells"]}
for element in raw["elements"]:
    centre = element.get("center")
    if not centre:
        continue
    col = math.floor((centre["lon"] - grid["westLng"]) * grid["metersPerDegreeLng"] / grid["cellM"])
    row = math.floor((grid["northLat"] - centre["lat"]) * grid["metersPerDegreeLat"] / grid["cellM"])
    key = f"r{row:02}-{col:02}"
    if key in counts:
        counts[key] += 1
exposure = {
    "source": "OpenStreetMap buildings via Overpass API",
    "license": "ODbL, (c) OpenStreetMap contributors",
    "osmTimestamp": raw["osm3s"]["timestamp_osm_base"],
    "totalBuildings": sum(counts.values()),
    "buildingsByCell": counts,
}
(ROOT / "src/data/bengaluru-exposure.ts").write_text(
    "// Generated by data/bengaluru/build_exposure.py.\nexport const BENGALURU_EXPOSURE = "
    + json.dumps(exposure, separators=(",", ":")) + " as const;\n")
print(json.dumps({"total": exposure["totalBuildings"], "max": max(counts.values()), "empty": sum(1 for v in counts.values() if v == 0)}))
