"""Build the 4-5 September 2022 Bengaluru replay: rainfall and reported flood places.

Run from the repository root with Python 3 (standard library only):
    python3 data/bengaluru/fetch_event_2022.py

Rainfall: ERA5 reanalysis (via Open-Meteo) gives the *timing* of the storm but,
at ~25 km resolution, badly under-reads convective totals (about 21 mm here).
IMD data reported by The Quint put the night's total at "more than 100 mm" over
Marathahalli, Doddanekkundi, Varthur and HAL Road. We therefore scale ERA5's
hourly shape to 100 mm, a conservative reading of that report (standard temporal
disaggregation). Reported flooded places are geocoded with OSM Nominatim.
"""
import json
import time
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RAW = ROOT / "data/bengaluru/raw"
OUT = ROOT / "src/data/event-2022.ts"
UA = {"User-Agent": "FlowShield-Hackathon-DataFetcher/1.0"}

NEWS = {
    "title": "Rains in Bengaluru Continue To Wreak Havoc, Bellandur Lake Overflows Into Homes",
    "publisher": "The Quint",
    "published": "2022-09-05",
    "url": "https://www.thequint.com/south-india/rains-in-bengaluru-continue-to-wreak-havoc-three-lakes-overflow-into-homes",
    "rainfallClaim": "Marathahalli, Doddanekkundi, Varthur and HAL road: more than 100 mm on Sunday night (IMD)",
}
REPORTED_TOTAL_MM = 100.0  # "more than 100 mm": use the conservative lower bound
EVENT_START = "2022-09-04T15:00"  # local time; the ERA5 storm runs 16:00-03:00
EVENT_HOURS = 18
# Places named as flooded in the article (geocoded below; outside-domain ones are kept and flagged).
PLACES = ["Bellandur", "Sarjapur Road", "Koramangala", "Indiranagar", "HAL Airport Road",
          "Rainbow Drive Layout", "Silk Board Junction"]


def get_json(url, cache):
    path = RAW / cache
    if not path.exists():
        with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=40) as r:
            path.write_bytes(r.read())
        time.sleep(1.2)  # Nominatim policy: at most one request per second
    return json.loads(path.read_text())


def main():
    era5 = get_json("https://archive-api.open-meteo.com/v1/archive?latitude=12.935&longitude=77.665"
                    "&start_date=2022-09-04&end_date=2022-09-05&hourly=precipitation&timezone=Asia%2FKolkata",
                    "era5-2022-09-04.json")
    times, values = era5["hourly"]["time"], era5["hourly"]["precipitation"]
    start = times.index(EVENT_START)
    shape = [v or 0.0 for v in values[start:start + EVENT_HOURS]]
    era5_total = sum(shape)
    scale = REPORTED_TOTAL_MM / era5_total
    hourly = [round(v * scale, 2) for v in shape]

    places = []
    for name in PLACES:
        q = urllib.parse.quote(f"{name}, Bengaluru")
        found = get_json(f"https://nominatim.openstreetmap.org/search?format=json&limit=1"
                         f"&viewbox=77.55,13.05,77.80,12.85&bounded=1&q={q}",
                         f"nominatim-{name.lower().replace(' ', '-')}.json")
        if found:
            places.append({"name": name, "lat": float(found[0]["lat"]), "lng": float(found[0]["lon"]),
                           "osmType": found[0]["type"]})

    event = {
        "id": "bengaluru-2022-09-04",
        "label": "Replay: 4-5 Sep 2022 flood",
        "startLocal": EVENT_START,
        "hourlyMm": hourly,
        "era5TotalMm": round(era5_total, 2),
        "scaledTotalMm": REPORTED_TOTAL_MM,
        "rainfallMethod": "ERA5 hourly timing scaled to an illustrative 100 mm, informed by news reporting; not a measured local hourly record",
        "news": NEWS,
        "reportedFloodedPlaces": places,
        "geocoder": "OpenStreetMap Nominatim",
    }
    OUT.write_text("// Generated by data/bengaluru/fetch_event_2022.py.\nexport const EVENT_2022 = "
                   + json.dumps(event, indent=2) + " as const;\n")
    print(json.dumps({"era5TotalMm": event["era5TotalMm"], "peakMmPerHour": max(hourly), "places": len(places)}))


if __name__ == "__main__":
    main()
