// Generated by data/bengaluru/fetch_event_2022.py.
export const EVENT_2022 = {
  "id": "bengaluru-2022-09-04",
  "label": "Replay: 4-5 Sep 2022 flood",
  "startLocal": "2022-09-04T15:00",
  "hourlyMm": [
    0.0,
    5.14,
    29.91,
    0.0,
    8.88,
    39.72,
    0.47,
    0.47,
    0.47,
    5.14,
    1.4,
    8.41,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0
  ],
  "era5TotalMm": 21.4,
  "scaledTotalMm": 100.0,
  "rainfallMethod": "ERA5 hourly timing (Open-Meteo archive) scaled to the IMD-reported total",
  "news": {
    "title": "Rains in Bengaluru Continue To Wreak Havoc, Bellandur Lake Overflows Into Homes",
    "publisher": "The Quint",
    "published": "2022-09-05",
    "url": "https://www.thequint.com/south-india/rains-in-bengaluru-continue-to-wreak-havoc-three-lakes-overflow-into-homes",
    "rainfallClaim": "Marathahalli, Doddanekkundi, Varthur and HAL road: more than 100 mm on Sunday night (IMD)"
  },
  "reportedFloodedPlaces": [
    {
      "name": "Bellandur",
      "lat": 12.9320495,
      "lng": 77.6842915,
      "osmType": "administrative"
    },
    {
      "name": "Sarjapur Road",
      "lat": 12.9244884,
      "lng": 77.6451418,
      "osmType": "primary"
    },
    {
      "name": "Koramangala",
      "lat": 12.9357366,
      "lng": 77.624081,
      "osmType": "suburb"
    },
    {
      "name": "Indiranagar",
      "lat": 12.9732913,
      "lng": 77.6404672,
      "osmType": "suburb"
    },
    {
      "name": "HAL Airport Road",
      "lat": 12.9616964,
      "lng": 77.6306978,
      "osmType": "primary"
    },
    {
      "name": "Rainbow Drive Layout",
      "lat": 12.9062184,
      "lng": 77.6868318,
      "osmType": "residential"
    },
    {
      "name": "Silk Board Junction",
      "lat": 12.9158955,
      "lng": 77.6239872,
      "osmType": "bus_stop"
    }
  ],
  "geocoder": "OpenStreetMap Nominatim"
} as const;
